// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2vE_UOW7B5klftL9SN33VqoTesIbcH7c',
    appId: '1:656532033168:android:9ee280a45ec14c3bd21215',
    messagingSenderId: '656532033168',
    projectId: 'kharis-app-47c49',
    storageBucket: 'kharis-app-47c49.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM-SqzIh-sfKtHeth-rqTK6T2DWzgOb40',
    appId: '1:656532033168:ios:cb96020b2434fcd5d21215',
    messagingSenderId: '656532033168',
    projectId: 'kharis-app-47c49',
    storageBucket: 'kharis-app-47c49.firebasestorage.app',
    iosBundleId: 'com.kharis.church',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrb8yD1g5rUAZR8fjuh_SXXhhgfyzKyNA',
    appId: '1:656532033168:web:8b84b12c3cd8d888d21215',
    messagingSenderId: '656532033168',
    projectId: 'kharis-app-47c49',
    authDomain: 'kharis-app-47c49.firebaseapp.com',
    storageBucket: 'kharis-app-47c49.firebasestorage.app',
    measurementId: 'G-VYRG23Z14G',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM-SqzIh-sfKtHeth-rqTK6T2DWzgOb40',
    appId: '1:656532033168:ios:cb96020b2434fcd5d21215',
    messagingSenderId: '656532033168',
    projectId: 'kharis-app-47c49',
    storageBucket: 'kharis-app-47c49.firebasestorage.app',
    iosBundleId: 'com.kharis.church',
  );
}
