// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-BfsQ5dGkmcYVX87QMDz5k0gAxDG9ETQ',
    appId: '1:193550520841:android:04df93075ac233e9689ed8',
    messagingSenderId: '193550520841',
    projectId: 'kharis-church',
    storageBucket: 'kharis-church.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApB73NdGgLA_cHk_DxT9gmSpijuiYuSI8',
    appId: '1:193550520841:ios:46ad20bca7b7964a689ed8',
    messagingSenderId: '193550520841',
    projectId: 'kharis-church',
    storageBucket: 'kharis-church.firebasestorage.app',
    iosBundleId: 'com.kharis.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSTb4h3uc2tf7-BqU9lKpZUT15OBZlXXQ',
    appId: '1:193550520841:web:869bfc2bb60d69e4689ed8',
    messagingSenderId: '193550520841',
    projectId: 'kharis-church',
    authDomain: 'kharis-church.firebaseapp.com',
    storageBucket: 'kharis-church.firebasestorage.app',
    measurementId: 'G-SXL76TWT0W',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApB73NdGgLA_cHk_DxT9gmSpijuiYuSI8',
    appId: '1:193550520841:ios:46ad20bca7b7964a689ed8',
    messagingSenderId: '193550520841',
    projectId: 'kharis-church',
    storageBucket: 'kharis-church.firebasestorage.app',
    iosBundleId: 'com.kharis.app',
  );
}
