// Motion One presets — generated by designlang (motionlang)
// Source: https://kharis.org
// 2026-06-07T21:53:51.478Z
//
//   import { animate } from 'motion';
//   import { animations, easings, durations } from './kharis.org-motion.one.js';
//
//   animations.fadeIn('#hero');
//   animations.slideUp('.card', { delay: 0.1 });

/** Easing curves extracted from the live page, as Motion One cubic-bezier arrays. */
export const easings = {
  custom1: [0.68, 0.01, 0.58, 0.75], // 92× on page
  easeOut: [0.165, 0.84, 0.44, 1], // 10× on page
  spring: [0.1, 0.76, 0.37, 1.19], // 10× on page
  easeInOut: [0.25, 0.1, 0.25, 1], // 5× on page
  custom7: [0.4, 0, 0.21, 0.99], // 1× on page
  linear: [0, 0, 1, 1], // 1× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  xs: 0.1,
  sm: 0.2,
  md: 0.27,
  lg: 0.45,
};

/** Motion One spring options — pass as the `type: 'spring'` block of an animate() call. */
export const springs = {
  soft: { type: 'spring', stiffness: 700, damping: 22, mass: 1 },
};

/** @keyframes blocks reconstructed as Motion One keyframe maps. */
export const keyframes = {
  sbySkScaleout: {
    "transform": ["scale(0)","scale(1)"]
  },
  sbySkScaleout: {
    "transform": ["scale(0)","scale(1)"]
  },
  testalt4: {
    "backgroundPosition": ["50% 80%","60% 70%","10% 10%","10% 10%","10% 40%","50% 80%"],
    "opacity": ["1","1","0.8","1","0.9","1"]
  },
  uicoreFadeIn: {
    "opacity": ["0","1"]
  },
  uicoreFloat: {
    "transform": ["translateZ(0px)","translate3d(0px, -7%, 0px)"]
  },
};

/** Animate-on-call helpers. Each takes a Motion One target + optional override. */
import { animate } from 'motion';

const _t = { duration: 0.27, easing: easings.custom1 };

export const animations = {
  fadeIn: (target, opts = {}) =>
    animate(target, { opacity: [0, 1] }, { ..._t, ...opts }),
  fadeOut: (target, opts = {}) =>
    animate(target, { opacity: [1, 0] }, { ..._t, ...opts }),
  slideUp: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], y: [16, 0] }, { ..._t, ...opts }),
  slideDown: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], y: [-16, 0] }, { ..._t, ...opts }),
  scaleIn: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], scale: [0.96, 1] }, { ..._t, ...opts }),
  pop: (target, opts = {}) =>
    animate(target, { scale: [0.9, 1] }, { ...springs.soft, ...opts }),
};

/** Site uses scroll- or view-timeline. Helpers wired to Motion One's `inView` / `scroll`. */
import { inView, scroll } from 'motion';

export const enterOnView = (target, variant = animations.slideUp) =>
  inView(target, (el) => { variant(el.target); });

export const parallaxY = (target, distance = 80) =>
  scroll(animate(target, { y: [0, -distance] }, { easing: 'linear' }));

export default { easings, durations, springs, keyframes, animations };
