// Framer Motion presets — generated by designlang (motionlang)
// Source: https://kharis.org
// 2026-06-07T21:53:51.477Z
//
//   import { transitions, variants } from './kharis.org-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  custom1: [0.68, 0.01, 0.58, 0.75], // 92× on page
  easeOut: [0.165, 0.84, 0.44, 1], // 10× on page
  spring: [0.1, 0.76, 0.37, 1.19], // 10× on page
  easeInOut: [0.25, 0.1, 0.25, 1], // 5× on page
  custom7: [0.4, 0, 0.21, 0.99], // 1× on page
  linear: [0, 0, 1, 1], // 1× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  xs: 0.1,
  sm: 0.2,
  md: 0.27,
  lg: 0.45,
};

/** Spring presets — pass to a Framer Motion `transition` prop. */
export const springs = {
  soft: { type: 'spring', stiffness: 700, damping: 22, mass: 1 },
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.27, ease: easings.custom1 },
  fast:  { duration: 0.135, ease: easings.custom1 },
  slow:  { duration: 0.486, ease: easings.custom1 },
  spring: springs.soft,
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  pop: {
    hidden: { opacity: 0, scale: 0.9 },
    show:   { opacity: 1, scale: 1, transition: springs.soft },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.068 } },
  },
  sbySkScaleout: {
    hidden: {},
    show: {
      "transform": ["scale(0)","scale(1)"],
      transition: transitions.base,
    },
  },
  sbySkScaleout: {
    hidden: {},
    show: {
      "transform": ["scale(0)","scale(1)"],
      transition: transitions.base,
    },
  },
  testalt4: {
    hidden: {},
    show: {
      "backgroundPosition": ["50% 80%","60% 70%","10% 10%","10% 10%","10% 40%","50% 80%"],
      "opacity": ["1","1","0.8","1","0.9","1"],
      transition: transitions.base,
    },
  },
  uicoreFadeIn: {
    hidden: {},
    show: {
      "opacity": ["0","1"],
      transition: transitions.base,
    },
  },
  uicoreFloat: {
    hidden: {},
    show: {
      "transform": ["translateZ(0px)","translate3d(0px, -7%, 0px)"],
      transition: transitions.base,
    },
  },
};

/** Site uses scroll- or view-timeline. Drop-in `whileInView` props. */
export const inView = {
  fadeIn: {
    initial: variants.fade.hidden,
    whileInView: variants.fade.show,
    viewport: { once: true, amount: 0.3 },
  },
  riseIn: {
    initial: variants.slideUp.hidden,
    whileInView: variants.slideUp.show,
    viewport: { once: true, amount: 0.3 },
  },
};

export default { easings, durations, springs, transitions, variants, inView };
