// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://kharis.org
// Generated: 2026-06-07T21:53:51.475Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#7a7a7a' | '#000000' | '#ffffff' | '#5f626a' | '#6b34fa' | '#32363d' | '#800654' | '#fd7f20' | '#8d8f93' | '#141b38' | '#d6ddeb' | '#babbc0' | '#999999' | '#3a4652' | '#d2d2d2' | '#202124';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Maven Pro' | 'DM Sans' | 'Times' | 'themify' | 'uicore-icons' | 'Noto Sans';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '700' | '900' | '300';

export type SpacingToken = '5px' | '15px' | '30px' | '38px' | '50px' | '60px' | '64px' | '80px' | '90px' | '100px' | '109px' | '130px' | '150px' | '250px';

export type RadiusToken = '3px' | '8px' | '12px' | '15px' | '18px' | '50px' | '100px' | '850px';

export type DurationToken = '100ms' | '200ms' | '270ms' | '450ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
